# Generated by Django 3.2.6 on 2021-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
