# Generated by Django 3.2.8 on 2021-10-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
