# Generated by Django 3.2.8 on 2021-10-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latest',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
