# Generated by Django 3.2.8 on 2021-10-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pre_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
