# Generated by Django 3.2.8 on 2021-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211013_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
