# Generated by Django 3.2.6 on 2021-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Business', 'Business'), ('Health & Fitness', 'Health & Fitness'), ('Travel', 'Travel')], max_length=100),
        ),
    ]
